dataset1:
  name: none
  data: none
  svg: none
dataset2:
  name: customData
  data: none
  svg: none
dataset3:
  name: customComputedData
  data: none
  svg: none
dataset4:
  name: brain_Prudencio
  data: example/expr_human.txt
  svg: example/homo_sapiens.brain.svg
dataset5:
  name: mouse_Merkin
  data: example/expr_mouse.txt
  svg: example/mus_musculus.male.svg
dataset6:
  name: chicken_Cardoso.Moreira
  data: example/expr_chicken.txt
  svg: example/gallus_gallus.svg
dataset7:
  name: shoot_Mustroph
  data: example/expr_arab.txt
  svg: example/arabidopsis.thaliana_shoot_shm.svg
dataset8:
  name: organ_Mustroph
  data: example/expr_arab.txt
  svg: example/arabidopsis.thaliana_organ_shm.svg
dataset9:
  name: root_Mustroph
  data: example/expr_arab.txt
  svg: example/arabidopsis.thaliana_root.cross_shm.svg
dataset10:
  name: shootRoot_Mustroph
  data: example/expr_arab.txt
  svg: example/arabidopsis.thaliana_shoot.root_shm.svg
dataset11:
  name: rootRootTip_Mustroph
  data: example/expr_arab.txt
  svg: example/arabidopsis.thaliana_root.roottip_shm.svg
dataset12:
  name: spatiotemporal_Narsai
  data: example/expr_coleoptile_samTimeCon.txt
  svg:
  - example/oryza.sativa_coleoptile.ANT_shm.svg
dataset13:
  name: growthStage_Mustroph
  data: example/random_data_multiple_aSVGs.txt
  svg:
  - example/arabidopsis.thaliana_organ_shm1.svg
  - example/arabidopsis.thaliana_organ_shm2.svg
dataset14:
  name: map_Census
  data: example/us_population2018.txt
  svg: example/us_map_shm.svg
title:
- title:spatialHeatmap
- width:350
max.upload.size: 5G 
default.dataset: organ_Mustroph
col.row.gene: None
separator: None
hide.legend: 'No'
data.matrix:
- A:0
- P:0
- CV1:-10000
- CV2:10000
- log.exp:No
- scale:Row
- row.selected:1
shm.img:
- height:350
- width:580
- columns:2
- display.by:gene
- preserve.scale:No
- color:yellow,orange,red
- color.scale:Selected rows
- file.type:NA
- dpi:300
- legend.width:0.7
- legend.aspect.ratio:1
- value.legend.rows:1
- value.legend.key:0.03
- value.legend.text:10
- include.feature:No
- line.color:grey70
- line.size:0.1
shm.anm:
- show:No
- transition:2
- height:NA
- width:770
shm.video:
- show:No
- transition:1
- height:0.9
- width:0.92
- dpi:400
- value.legend:No
- dimension:640x480
legend:
- key.row:2
- key.size:0.04
- label:No
- label.size:2.5
mhm:
- measure:correlation
- cor.absolute:No
- select.by:p
- cutoff:0.2
- scale:No
network:
- color:yellow,orange,red
- net.type:signed
- min.size:15
- ds:3
- max.edges:10
download_single:
  data: example/expr_arab.txt
  svg: example/arabidopsis.thaliana_shoot_shm.svg
download_multiple:
  data: example/random_data_multiple_aSVGs.txt
  svg:
  - example/arabidopsis.thaliana_organ_shm1.svg
  - example/arabidopsis.thaliana_organ_shm2.svg
download_spatial_temporal:
  data: example/expr_coleoptile_samTimeCon.txt
  svg: example/oryza.sativa_coleoptile.ANT_shm.svg
