dataset1:
  name: NONE
  data: NONE
  svg: NONE
dataset3:
  name: FIELD
  data: example/FIELD.csv
  svg: example/FIELD.svg
dataset4:
  name: PLATE
  data: example/PLATE.csv
  svg: example/PLATE.svg
dataset5:
  name: GH.SUB
  data: example/GHSUB.csv
  svg: example/GHSUB.svg
dataset6:
  name: GH.W.D.WL
  data: example/GHWDWL.csv
  svg: example/GHWDWL.svg
title:
- title:spatialHeatmap
- width:350
max.upload.size: 5G
default.dataset: FIELD
col.row.gene: None
separator: None
data.matrix:
- A:0
- P:0
- CV1:-10000
- CV2:10000
- log.exp:No
- scale:No
- selected.id:OS01G0100100
shm.img:
- columns:2
- display.by:gene
- scale.plots:1.4
- title.size:12
- relative.size:1
- color:yellow,orange,red
- color.scale:Selected rows
- file.type:NA
- dpi:300
- include.legend.plot:Yes
- legend.plot.size:0.5
- value.legend.rows:1
- value.legend.key:0.03
- value.legend.text:10
- include.feature:No
- line.color:grey70
- line.size:0.02
shm.anm:
- transition:2
- scale.plot:1
shm.video:
- show:No
- transition:1
- dpi:400
- key.rows:2
- key.size:0.04
- value.legend:No
- feature.label:No
- label.size:2
- dimension:640x480
- bar.width.video:0.1
legend:
- key.row:2
- key.size:0.04
- label:No
- label.size:2.5
- aspect.ratio:1
mhm:
- measure:correlation
- cor.absolute:No
- select.by:p
- cutoff:0.2
- scale:No
network:
- color:yellow,orange,red
- net.type:signed
- min.size:15
- ds:3
- max.edges:10
download_single:
  data: example/expr_arab.txt
  svg: example/arabidopsis.thaliana_shoot_shm.svg
download_multiple:
  data: example/random_data_multiple_aSVGs.txt
  svg:
  - example/arabidopsis.thaliana_organ_shm1.svg
  - example/arabidopsis.thaliana_organ_shm2.svg
download_spatial_temporal:
  data: example/expr_coleoptile_samTimeCon.txt
  svg: example/oryza.sativa_coleoptile.ANT_shm.svg
download_batched_data_aSVGs:
  data: example/aSVGs_shm.tar
  svg: example/data_shm.tar
